### ISSUE TITLE
Adoption of testinfra plugin to pytest-dev organization

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/meta#1]
I would like to propose migration of testinfra plugin under pytest-dev. This was already proposed to the author and he was willing to transfer.

Still there is one minor issue, as the project is quite old and established, he does not want to rename the repository to match the `pytest-` prefix rule we have plugins.

I do personally think that we can make one exception, on the ground of being a historical name (more than 4 years in production). IMHO, keeping most popular pytest plugins in a single place helps not only with maintenance but also with with making pytest better known and trustable. 

This was proposed about an year ago at https://github.com/philpep/testinfra/issues/484 but I think we never got an answer from pytest-dev team.

**Comment by asottile** [comment]
hmm so this is tricky:

- [ ] PyPI presence with a setup.py that contains a license, pytest- prefixed name, version number, authors, short and long description. **(yes, except the [naming requirement](https://github.com/philpep/testinfra/blob/cd485d4360f13bbddfc7848576c874f585cbfa32/setup.cfg#L2))**
- [x] a tox.ini for running tests using tox. **([yes](https://github.com/philpep/testinfra/blob/cd485d4360f13bbddfc7848576c874f585cbfa32/tox.ini))**
- [x] a README.txt describing how to use the plugin and on which platforms it runs. **([yes](https://github.com/philpep/testinfra/blob/cd485d4360f13bbddfc7848576c874f585cbfa32/README.rst), though I couldn't find platform information anywhere)**
- [x] a LICENSE.txt file or equivalent containing the licensing information, with matching info in setup.py. **([yes](https://github.com/philpep/testinfra/blob/cd485d4360f13bbddfc7848576c874f585cbfa32/setup.cfg#L9))**
- [x] an issue tracker for bug reports and enhancement requests. **([yes](https://github.com/philpep/testinfra/issues))**
- [x] a changelog. **([yes](https://github.com/philpep/testinfra/blob/cd485d4360f13bbddfc7848576c874f585cbfa32/CHANGELOG.rst))**

all of the other pytest plugins in pytest-dev satisfy the naming requirement, we've not made this exception before

**Comment by asottile** [comment]
to be clear, I'm not -1 on this (somewhere around -0 but easily convinced to a +1), but it doesn't meet the requirements.

**Comment by nicoddemus** [comment]
I don't mind either, unless someone else feels strongly against it.

**Comment by philpep** [comment]
Hi, testinfra author here, thanks for feedback !

For now renaming the project on pypi and renaming the python module in a clean way seems quite complex. But I'm not opposed to do it at a time.

Would it be possible to start by moving the github project to pytest-dev/testinfra (preferabily from my pov) or pytest-dev/pytest-testinfra (including issues/PR/followers) ? So we can move forward, checking that travis/pypi uploads/readthedocs works, maintainers etc.

PS: You can contact us on freenode #pylib : philpep and/or zbr

**Comment by ssbarnea** [comment]
@pytest-dev/core Any of you available today, maybe we can finally make a decision?

**Comment by RonnyPfannschmidt** [comment]
I'm currently out with the toddler but if we agree on a rename time line we can sort it in the evening

**Comment by philpep** [comment]
@RonnyPfannschmidt ok thanks

IIUC, the process is:

* for me, "transfer ownership" to ~~pytest-dev organization~~ @RonnyPfannschmidt 
* for you accept transfer (and rename to pytest-dev/pytest-testinfra, or should I rename the github project before transfer ?)
* Add myself and @ssbarnea as owner of the repository.

Is that correct ?

On our side we will rename the project on pypi to pytest-testinfra, while keeping the module name to "testinfra".
Just ping us when I can transfer ownership.

**Comment by ssbarnea** [comment]
Thanks @RonnyPfannschmidt we can consider this done! We still have other boring maintenance to do post move.
