### ISSUE TITLE
Adoption of pytest-sugar plugin to pytest-dev organization

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/meta#5]
This used to track https://github.com/Teemu/pytest-sugar/issues/184 which is mainly about transfer of pytest-sugar plugin under pytest-dev org.

I think that the plugin already matches the documented requirements so it should be easy.

@RonnyPfannschmidt told me he could help with the move later in the week so it would be a good idea to add him to the source repo.

**Comment by RonnyPfannschmidt** [comment]
@ssbarnea i just stumbled on this one again, is there anything i can do atm

**Comment by ssbarnea** [comment]
Nope. We still wait for @Teemu to answer. I did add a comment there.

**Comment by RonnyPfannschmidt** [comment]
closing, project is just alive again with new maintainers, they can request once they feel its good

**Comment by ssbarnea** [comment]
@RonnyPfannschmidt I think that the recent moves of plugins to pytest-dev do not only help these projects but the entire ecosystem. I like to see how pytest-dev kinda replicates jazzband approach.

Shortly 2023 looks very green for pytest users!
