### ISSUE TITLE
Adopt pytest-order into pytest-dev

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/meta#7]
That is a tracking issue around for https://github.com/mrbean-bremen/pytest-order/issues/4 

@pytest-dev/core please comment on this.

**Comment by nicoddemus** [comment]
My answer in https://github.com/ftobia/pytest-ordering/issues/32#issuecomment-715257657 still stands.

cc @ftobia

**Comment by ssbarnea** [comment]
Sure. I only wanted to have a centralized place to track adoptions.

**Comment by mrbean-bremen** [comment]
@nicoddemus - I would like to go ahead with the transfer, if that is ok. I haven't got a response from the maintainer of the original package so far. What do you think?

**Comment by nicoddemus** [comment]
Sure, let's go ahead then, we have left enough time for the original maintainer to reply. 👍

**Comment by mrbean-bremen** [comment]
Thanks! I just subscribed to pytest-dev and wrote a respective mail, is there anything else to do for me at the moment?

**Comment by nicoddemus** [comment]
Let's follow proper protocol and wait for others to 👍, should take a day max.

**Comment by The-Compiler** [comment]
Looks good, please go ahead!

**Comment by mrbean-bremen** [comment]
@nicoddemus - thanks, I will just wait for a go or no-go then.

**Comment by nicoddemus** [comment]
Please go ahead! The "proper" protocol is for people to respond to the mailing list, but of course responding here in the issue also works. 👍

**Comment by mrbean-bremen** [comment]
Thanks 😃. So... if I understand this correctly, I shall transfer the ownership to a pytest-dev admin, e.g. to you. Is this correct, or is there something else to do before that?

**Comment by nicoddemus** [comment]
That's it! I will then accept the transfer, and add you as maintainer under the new location. 👍

**Comment by nicoddemus** [comment]
Transfer complete! Any lingering issue we can open new issues in the new repository location itself. 👍 

Thanks everyone!
